import os

observationList = [
    #"John went to the beach",
    #"John bought 17 watermelons with his Capital One Credit Card",
    #"John gave $350,000 to openAI, while laughing at competitor's LLMs",
    #"John believes in the heart of the cards, Yugi-boy",
    #"John has expanded his consciousness to another plane of existence, interacting with the world purely through astral projection and sheer force of will",
    #"John has opened his 3rd eye, unlocking deep secrets previously withheld from human existence",
    #"John watches the news, but only in languages he can't understand",
    #"John tried to run for local governor, but stopped after being told it would still be illegal for him to commit crimes",
    #"John broke the 4th wall, and realized that he is an imaginary character in a simulation for a class project",
    #"John does not eat his vegetables",
    #"John owns 23 tractors, and names each of them after old rock & roll bands",
    #"John prefers Pepsi over Coke",
    "Last week, I saw John worked overtime at his job and ending up going home a few hours late, missing dinner",
    "I heard that John spent his yearly bonus from his job on a ski trip to Aspen with his family",
    "Last time I visited John, I saw he had a comprehensive home gym complete with a weight set, bench, and squat rack",
    "Yesterday at the bar, I overheard John talking about how big the lottery jackpot was getting and that he was considering buying a lot of tickets for a chance to win",
    "A few months ago, I heard John got a job offer overseas in Lebanon. The pay was great, but John said it was too risky to move there until the tension in the area settled down.",
    "Last month, John told me about his favorite hobbies -- sky-diving, spearfishing, and mountain biking.",
    "I overheard John's boss threatening to fire him -- apparently, John clocked in an hour late last week so that he could drop his kids off at summer camp",
    "John cancelled our weekend plans to go fishing so that he could spend the time with his wife after her father passed away",
    "John was nowhere to be seen when his son gave his first piano recital -- apparently, he hadn't finished his work for the day and was forced to stay late",
    "John was super excited about picking up painting last year, but, from what I can tell, he can't seem to fully finish a painting before getting bored and moving on to the next",
    "John got a promotion at his job this year, and was given recognition for selling the most houses of any realtor",
    "Last time I tried to hold a conversation with John, he kept getting distracted by the football game on the T.V.",
]